(defun nthelement (*list* position)
    (if (< position 1)
        (values nil)
        (values (nth (- position 1) *list*))
    )
)

(defun accept-list ()
    (format t "Enter a list [end it with typing nil]:")
    (terpri)
    (defparameter a nil)
    (setf *list* (list))
    (loop
        (setf a (read))
        (setf *list* (append *list* (list a)))
        (when (eq a 'nil)(return *list*))
    )
    (setf *list* (remove 'nil *list*))
    (values *list*)
)

(defvar *list* nil)
(setf *list* (accept-list))
(format t "Entered List: ~a" *list*)
(terpri)
(format t "Enter the position: ")
(print (nthelement *list* (read)))
